### ISSUE TITLE
Support for Scala 3

### ISSUE THREAD

**Issue by codepitbull** [vert-x3/vertx-lang-scala#104]
# Description

The current codebase must be adapted to work with Scala 3.

# Acceptance criteria

Everything we currently have is based on Scala 3.

**Comment by miteshaghera** [comment]
@codepitbull I would like to contribute for supporting scala 3 in vert.x 4. Have you started anything or is there any plan?

**Comment by vietj** [comment]
@miteshaghera you should join the vertx discord server and get in touch in the scala channel to catch up the discussion
