### ISSUE TITLE
Add support for '.scala. file

### ISSUE THREAD

**Issue by cescoffier** [vert-x3/vertx-lang-scala#11]
When deploying non-compiled scala verticles, the factory should compile them. This would improve the usage of Scala verticle when using the `vertx` CLI:

For instance:

```
vertx run MyVerticle.scala --redeploy="*.scala"
```

**Comment by codepitbull** [comment]
The current version of scala-on-the-fly already supports this internally but I need to do some thorough testing to see if there are any classloader leaks before making it available.
