### ISSUE TITLE
How could I pass a Scala handler to Scala Route?

### ISSUE THREAD

**Issue by honeyAndSw** [vert-x3/vertx-lang-scala#17]
It looks like there's a mismatch between Route.handler interface and documentation.
According to the [vertx-web-scala document](https://github.com/vert-x3/vertx-lang-scala/blob/master/vertx-lang-scala-stack/vertx-web/src/main/asciidoc/scala/index.adoc), for example, StaticHandler could be used like this:
```scala
import io.vertx.scala.ext.web.Router
import io.vertx.scala.ext.web.handler.StaticHandler

router.route("/static/*").handler(StaticHandler.create())
```

However, `StaticHandler.create()` returns `StaticHandler` object, which `Route.handler()` signature doesn't allow to pass.
```scala
def handler(requestHandler : scala.Function1[io.vertx.scala.ext.web.RoutingContext, scala.Unit])
   : io.vertx.scala.ext.web.Route
```

So I had to do **Java conversion**, then use Java StaticHandler.
```scala
import io.vertx.scala.ext.web.Router
import io.vertx.ext.web.handler.StaticHandler

router.route("/*").asJava.handler(StaticHandler.create())
```

**Comment by gitplaneta** [comment]
I had a similar issue. I've ended up with just calling the .handler(_) method, like this:

`router.route("/static/*").handler(StaticHandler.create().handle(_))`

**Comment by honeyAndSw** [comment]
@gitplaneta Better way than mine! Thanks for sharing 😄

**Comment by codepitbull** [comment]
Sorry for the late response.
I have focused on vertx-core and I am currently going through all the modules.
It will be possible to use StaticHandler directly after I refactored some of the Handler-generation code.
Stay tuned :)

**Comment by codepitbull** [comment]
Fixed in current SNAPSHOTs.
See updated examples in https://github.com/codepitbull/vertx-scala-sbt
