### ISSUE TITLE
Stable release for 4.5.11?

### ISSUE THREAD

**Issue by zaninime** [vert-x3/vertx-lang-scala#207]
Hey @oliver-brm, thanks for the project first of all!

I am planning on using it in a build, however `-SNAPSHOT` dependencies are mutable and [they make builds slower and brittle](https://www.scala-sbt.org/1.x/docs/Dependency-Management-Flow.html#Notes+on+SNAPSHOTs).

Could you cut a release for 4.5.11? I can prepare a PR for the version change, however you'll still have to tag it and push it.

It would also help the related `g8` template.

Let me know what you think!

**Comment by oliver-brm** [comment]
Thanks for your interest in vert-lang-scala and for your kind words! Let's thank all the contributors. I'm currently only keeping this code up to date with the latest Vert.x 4.x and 5.x versions...

Sure, we need a release. I'm currently in discussion with the project leader and need to fix some things in the 4.x branch. I'm looking forward to see this stuff in Maven Central.

**Comment by oliver-brm** [comment]
Here we are - `vertx-lang-scala` 4.5.11 is released! Grab it while it's hot and have fun with it!

**Comment by zaninime** [comment]
Thanks so much!
