### ISSUE TITLE
[3.4.1] routingContext.statusCode can't get right statusCode

### ISSUE THREAD

**Issue by leopard7777777** [vert-x3/vertx-lang-scala#35]
```scala
routingContext.statusCode()
```
is always 0 
```scala
routingContext.asJava.asInstanceOf[RoutingContextImpl].statusCode()
```
can be right
![p](https://cloud.githubusercontent.com/assets/11750796/24598593/c1440bb0-187e-11e7-91c6-ddd932c906e5.png)

**Comment by codepitbull** [comment]
I will take a look at this tomorrow.

**Comment by codepitbull** [comment]
I have a reproducer, will investigate where the code gets lost.
