### ISSUE TITLE
Code executed on VertxExecutionContext not runs on event loop

### ISSUE THREAD

**Issue by zella** [vert-x3/vertx-lang-scala#39]
I expect, that future result, computated on global context will be called on event loop, as I clearly specify `executionContext` in `onSucsess`. But it calls on my computation context.

```
class HttpVerticle extends ScalaVerticle {
  
  override def startFuture(): Future[Unit] = {
    //Create a router to answer GET-requests to "/hello" with "world"
    val router = Router.router(vertx)
    val route = router
      .get("/hello")
      .handler((ctx: RoutingContext) => {
        Future {
          Thread.sleep(1000)
          "computed"
        }(ExecutionContext.global)
          .onSuccess {
           //here calls on global context
            case s => println(Thread.currentThread().getName); ctx.response().end(s)  
          }(executionContext)
      })

    vertx
      .createHttpServer()
      .requestHandler(router.accept)
      .listenFuture(8666, "0.0.0.0")
      .map(_ => ())
  }
}
```

Perhaps, it because
https://github.com/vert-x3/vertx-lang-scala/blob/master/vertx-lang-scala/src/main/scala/io/vertx/lang/scala/VertxExecutionContext.scala#L35

don't calls on vertx context?

**Comment by codepitbull** [comment]
You are right. I fixed it and it will be part of 3.4.2.
You can use it with the current SNAPSHOTS (should end up in our repos soon).

Thanks for reporting, especially with a reproducer!
