### ISSUE TITLE
Scala class should implement Handler via mixin when it has super types

### ISSUE THREAD

**Issue by tsegismont** [vert-x3/vertx-lang-scala#49]
Since eclipse/vert.x#2106 is merge, build fails because Scala class has the keyword `override` on method `handle` but it does extend `Handler`.

The template must be changed to implement `Handler` via mixin when Vert.x core class extends a another API type and implements `Handler`.

**Comment by codepitbull** [comment]
Fixed via https://github.com/vert-x3/vertx-lang-scala/pull/52
