### ISSUE TITLE
info about vertx and slick async (slick 3.0)

### ISSUE THREAD

**Issue by cocodrino** [vert-x3/vertx-lang-scala#5]
Hi galder, the new slick version includes a thread pool allowing do async request, really cool, the problem is than this approach collide with vertx architecture, http://slick.typesafe.com/doc/3.0.0-M1/database.html#using-typesafe-config , I know than you did some researchs about how run futures inside vertx and I think than would be possible a similar approach with slick because it also has an AsyncContext, but sincerally I don't know much about these concepts..

do you think than is possible/simple use this new slick feature inside vertx??...thanks!!.....

**Comment by galderz** [comment]
Why does it collide exactly? Are you getting any errors/problems?

**Comment by codepitbull** [comment]
This issue is based on a version of vertx-lang-scala that doesn't exist any more.
Closing it.
