### ISSUE TITLE
Vert.x web does not compile because of bridge classes

### ISSUE THREAD

**Issue by tsegismont** [vert-x3/vertx-lang-scala#51]
In https://github.com/vert-x3/vertx-web/commit/961c2ce bridge classes have been deprecated and updated to extend the `web-common` classes.

This [breaks](https://vertx.ci.cloudbees.com/view/vert.x-3/job/vert.x3-lang-scala/743/) the `lang-scala` build.

**Comment by tsegismont** [comment]
@codepitbull can you please take a look? I'm not yet comfortable enough to try to fix that one. Thanks

**Comment by codepitbull** [comment]
Fixed with https://github.com/vert-x3/vertx-lang-scala/pull/52
