### ISSUE TITLE
Allow to deploy a ScalaVerticle instance directly

### ISSUE THREAD

**Issue by giampaolotrapasso** [vert-x3/vertx-lang-scala#53]
Would be nice to extend `Vertx#deployVerticle` passing directly an instance of `ScalaVerticle` as is possible in the Java version. This would allow, for example, to do DI of already instantiated services passing them into the constructor of the new deployed verticle.

Is this possible or am I asking for something that breaks Vert.x philosophy? 

btw, thanks @codepitbull for the great porting!

**Comment by codepitbull** [comment]
Sounds like a good idea to me. The methods you mentioned that exist in the Java version are actually excluded from auto-generation so I need to provide something explicitly.

**Comment by codepitbull** [comment]
I just added the methods you proposed in your PR. The ones using a Handler for completion are now replaced with methods returning a Future.
The changes will be available some time tonight with 3.5.1-SNAPSHOT.


Thanks for your work :)
