### ISSUE TITLE
Use Value Objects

### ISSUE THREAD

**Issue by mslinn** [vert-x3/vertx-lang-scala#57]
In other words, domain objects should extend `AnyVal`. Scala value objects have no runtime cost (for example, no boxing or unboxing) when used as is currently done in `vertx-lang-scala`.

`io.vertx.scala.ext.web.handler.BodyHandler` is an example. This type should be implemented as a case class with a public property, and the property should probably be of type `io.vertx.ext.web.handler.BodyHandler`:

    package io.vertx.scala.ext.web.handler

    import io.vertx.ext.web.handler.{BodyHandler => JBodyHandler}
    
    case class BodyHandler(value: JBodyHandler) extends AnyVal {
      override def toString: String = value
    }

This would simplify other library and application code, and would be more idiomatic Scala. There would be no need for an `asJava` method, and the implementation could dispense with all the occurances of `asInstanceOf[JBodyHandler]`, which unfortunately the current implementation also forces on application code. 

In fact, all of the casts in this method should be eliminated, and this can be done easily. As written, the library code overrides type safety, and this is both undesirable and unnecessary.

This pattern can be found in other areas of the same library, for example `JDBCClient.create`. Currently one must write:

     JDBCClient(JJDBCClient.create(vertx.asJava.asInstanceOf[io.vertx.core.Vertx], dataSource))

instead of the typesafe and succinct expression:

     JDBCClient(vertx, dataSource)

**Comment by codepitbull** [comment]
Yes, this is still a sore point.
Changing it involves some deeper restructuring of the way the adapters are generated.
The crux is that there several places during code-generation where I have to rely on conventions rather than actual type information.
The recent additions in the codegen-part of Vert.x might provide this information and I will hopefully be able to resolve those.
I will give it another go after xmas :)

Thanks for reporting and providing some good examples!

**Comment by codepitbull** [comment]
Got some time to look at your recommendation.
The problem with your approach is that I am losing important type information.
The BodyHandler is supposed to be used as a Handler on the Vertx-Web-Router. Using AnyVal gets rid of that information and would require to make the Router-API less explicit by making it accept an AnyVal.

**Comment by mslinn** [comment]
Extending `AnyVa`l does not mean that one would consider `AnyVal` as superclass. Instead, Scala uses `AnyVal` to indicate that the derived class should be considered as an ephemeral value object. [Here is some dated information](https://docs.scala-lang.org/overviews/core/value-classes.html). [My Internediate Scala Course](https://www.scalacourses.com/student/showLecture/72) goes into this in detail.

**Comment by codepitbull** [comment]
Sorry for the delay. 
You are obviously right. Have been using that pattern with type-classes, never realizing the allocation impact (my bad for not listening and simply copying the pattern ...).
I started work on using this by creating package objects and implicit classes which should make it easily usable.
I hit some limitations in our codegen which I fixed. I am currently waiting for the PR (https://github.com/vert-x3/vertx-codegen/pull/148) to get merged.
Depending on my workload I should be able to have a working example for the improved API sometime next week.

So stay tuned, change is coming :)

**Comment by codepitbull** [comment]
To keep everyone posted on this:
I started to work on a new version using implicit value classes.
The (very earyl) version is here:
https://github.com/codepitbull/vertx-lang-scala-vc
It's gonna take a while until work is even close to be being finalized as I have to rewrite most of what I've done so far.

**Comment by codepitbull** [comment]
There is a new preview version of the Scala integration.
It uses Value Objects and is available here:
https://github.com/vert-x3/vertx-lang-scala/tree/4.0

Closing this as this won't be backported to Vert.x 3.
