### ISSUE TITLE
Update docs to mention PKCS12 instead of JCEKS

### ISSUE THREAD

**Issue by mslinn** [vert-x3/vertx-lang-scala#58]
The [docs show examples](https://github.com/vert-x3/vertx-lang-scala/blob/master/vertx-lang-scala-stack/vertx-auth-jwt/src/main/asciidoc/scala/index.adoc#generate-a-new-keystore-file) of how to generate keystore files. Running the suggested `keytool` commands yields the following warning:

```
$ keytool -genseckey -keystore keystore.jceks -storetype jceks -storepass secret \
    -keyalg HMacSHA256 -keysize 2048 -alias HS256 -keypass secret

Warning:
The JCEKS keystore uses a proprietary format. 
It is recommended to migrate to PKCS12 which is an industry standard format using 
"keytool -importkeystore -srckeystore keystore.jceks -destkeystore keystore.jceks -deststoretype pkcs12".
```

Seems that modifying the examples to follow the advice in the warning would be a good idea. This would also require modifying the [JWT Authorization code example](https://github.com/vert-x3/vertx-lang-scala/blob/master/vertx-lang-scala-stack/vertx-web/src/main/asciidoc/scala/index.adoc#jwt-authorisation) so references to JCEKS are updated to PKCS12.

BTW, [JDK 9 uses PKCS12 by default](http://openjdk.java.net/jeps/229), and [Oracle recommends using openssl instead of keytool](https://docs.oracle.com/cd/E19509-01/820-3503/ggfhb/index.html).

**Comment by codepitbull** [comment]
This is currently being discussed in the dev-mailinglist.
The lang-implementations themselves can't cahnge that as we relly on what is provided by vertx-core, both code and documentation-wise (docs are also generated from the vert.x base docs).

See the discussion here: https://mail.google.com/mail/u/0/#label/vertx-dev/160571b91832215a

I will keep this issue open for tracking purposes.

**Comment by mslinn** [comment]
@codepitbull The link you gave is to your private mailbox. If [this](https://groups.google.com/forum/#!topic/vertx-dev/SHXCvf-lass) is the link you meant to share, it does not discuss PKCS12 and does not mention that Java keystores do not support PKCS12. The link I provided shows that Oracle is essentially saying that the Java keytool program is dead. I don't think the participants on the discussion know this.

**Comment by codepitbull** [comment]
You are right. Still, vertx-lang-scala is thew wrong project to file the issue with.
I took the freedom and copied your initial comment and created an issue against vertx-web

https://github.com/vert-x3/vertx-web/issues/792

**Comment by mslinn** [comment]
Thank you!
