### ISSUE TITLE
VertxOptions not having ***setClusterManager*** function

### ISSUE THREAD

**Issue by blueberrynotblue** [vert-x3/vertx-lang-scala#63]
I read official doc about vertx-hazelcast in which code written by java.
I found io.vertx.scala.core.VertxOptions not having **setClusterManager** function
```
env:
Scala       = "2.12.1"
ScalaTest   = "3.0.1"
Vertx       = "3.5.0"
vertx_lang_scala
vertx_hazelcast
```

I think vertx-hazelcast official doc should be more detailed.

**Comment by codepitbull** [comment]
Looks like a problem in vertx-codegen. I opened an issue there (https://github.com/vert-x3/vertx-codegen/issues/157) but I am not sure we will be able to resolve it for 3.5.1

**Comment by blueberrynotblue** [comment]
Any idea to work this around?

**Comment by codepitbull** [comment]
As a workaround you can grab the underlyikng Java-object and invokle the method directly:
`VertxOptions().asJava.setClusterManager(...)`

**Comment by codepitbull** [comment]
Closing since there is a usable workaround for 3.x and because this issue isn't showing up in the new implementation for 4.
