### ISSUE TITLE
I can't build the project. I get dependency errors.

### ISSUE THREAD

**Issue by ar-zare** [vert-x3/vertx-lang-scala#7]
Could not resolve dependencies for project io.vertx:vertx-lang-scala:jar:3.0.0-SNAPSHOT: The following artifacts could not be resolved: io.vertx:vertx-codegen:jar:sources:3.0.0-SNAPSHOT,

**Comment by cescoffier** [comment]
You need to update to the 3.0.0 version (or 3.1.0-SNAPSHOT).

**Comment by cescoffier** [comment]
Any feedback ?

**Comment by ar-zare** [comment]
It still doesnt work.I will later send you more details. Thanks for your mail.Best regads,AlirezaVerzonden vanaf mijn Huawei mobiele telefoon-------- Oorspronkelijk bericht --------Onderwerp: Re: [vertx-lang-scala] I can't build the project. I get dependency errors. (#7)Van: Clement Escoffier Aan: vert-x3/vertx-lang-scala Cc: Alireza Zare Any feedback ?
