### ISSUE TITLE
Register a codec

### ISSUE THREAD

**Issue by lecogiteur** [vert-x3/vertx-lang-scala#73]
Hi,

It seems we can't add a codec from Vert.x Scala API. We need to retrieve Vert.x Java API in order to add a codec.
I saw the issue #60 is closed but it seems it doesn't do it.

My version 3.5.3

**Comment by codepitbull** [comment]
Sorry for the delay. I was working on the new generator for vertx-lang-scala.

You are absolutely right, this is a regression.

It is fixed in the new generator which will be merged into the current master soon.
This will then be released together with the next vert.x-release.
Thanks for reporting!
