### ISSUE TITLE
Confusion between scala Future and vertx Future 

### ISSUE THREAD

**Issue by inmyth** [vert-x3/vertx-lang-scala#75]
I notice that in some cases Futures from `scala.concurrent.Future` and `io.vertx.scala.Future` have been confused with each other. 
One example is MessageConsumer (used primarily by Handler) and Verticle's startFuture (addressed by #43 ) which both return `scala.concurrent.Future`  whereas CompositeFuture takes in `io.vertx.scala.Future`. As such CompositeFeature cannot be used to group and asynchronously run Futures from verticle deployment.

**Comment by codepitbull** [comment]
They are not confused, it was a deliberate choice to do so.

`CompositeFuture` and `io.vertx.Future` are left overs from the beginning of Vert.x 3. It was initially developed on JDK 1.7 so these classes were added to deal with the lack of a CompletableFuture. 
They are in there to stay compatible with other parts of Vert.x which might not have switched over to other means.

In Scala we already have several ways of dealing with multiple Futures and those are the ones I recommend, so don't bother with CompositeFuture as it doesn't play well with Scala at all.

So, if you have multiple `scala.concurrent.Future` there are two ways of combining them:

1. Use a for-comprehension:
```
val f1:Future = ...
val f2:Future = ...

val combined = for{
  result1 <- f1
  result2 <- f2
} yield (result1, result2)
```

2. Use Future.sequence
The Scala-Future already provides a way to handle multiple futures. Check the [ScalaDoc](https://www.scala-lang.org/api/current/scala/concurrent/Future$.html#sequence[A,M[X]%3C:TraversableOnce[X]](in:M[scala.concurrent.Future[A]])(implicitcbf:scala.collection.generic.CanBuildFrom[M[scala.concurrent.Future[A]],A,M[A]],implicitexecutor:scala.concurrent.ExecutionContext):scala.concurrent.Future[M[A]])
