### ISSUE TITLE
vertx-web blockingHandler or Scala Future ? 

### ISSUE THREAD

**Issue by inmyth** [vert-x3/vertx-lang-scala#76]
vertx-web instruction says that for blocking operation we need to use blockingHandler (to avoid blocking the main event loop). Does this requirement apply on Future ? For example, is the code below still considered blocking ? 
    
    router.get("/a").handler(ctx => {
      val f = for {
        f1 <- ...
        f2 <- ...
      } yield f2
      f onComplete {
         case Success(b) => ctx.response.end("ok")
         case Failure(e) => ctx.response.end("not ok")
      }
    })

**Comment by codepitbull** [comment]
Sorry for the late replay but I still think a few things should be cleared up.
First of all: 
There is am implict [ExcutionContext](https://github.com/vert-x3/vertx-lang-scala/blob/master/vertx-lang-scala/src/main/scala/io/vertx/lang/scala/VertxExecutionContext.scala) inside a Verticle.
This is used to reschedule work on the Event Loop, work  that is supposed to be non blocking.
Vert.x has the notion of worker threads and that's where the blocking handler comes in.
A blockingHanlder is sued to move blocking work outside the event loop into a worker thread.
Remember: The event loop must never block.

Creating your own pools and use them with Scalas Future/Promises is perfectly fine, blockinghandler mainly exists as we map all Java-methods through to the Scala layer.
