### ISSUE TITLE
Remove unused imports warning during build

### ISSUE THREAD

**Issue by vietj** [vert-x3/vertx-lang-scala#77]
The current scala compilation emits lot of unused imports during the build. Such warnings are not really useful and they produce lot of verbosity, raising issues with Travis CI.

**Comment by vietj** [comment]
@codepitbull is that something you can handle soon ?

**Comment by codepitbull** [comment]
Not soon but in the longer run.
It's not that easy to get rid of those.
I will have a look when I get some time.

**Comment by vietj** [comment]
actually I meant that the compiler does not emit them :-)

**Comment by codepitbull** [comment]
I ahve reduced the WARNING noise as much as possible, sadly the Scalac won't disable all of them and it doesn't look it will do so in the near future.
