### ISSUE TITLE
Handlers cannot be unset

### ISSUE THREAD

**Issue by sumnulu** [vert-x3/vertx-lang-scala#81]
Example:
`response.handler(null)`  will not work as intended (to release the reference) because scala api will wrap it with a new function 

 io.vertx.scala.core.http.HttpClientResponse#handler
```
  def handler(handler: Handler[io.vertx.core.buffer.Buffer]): HttpClientResponse = {
    asJava.asInstanceOf[JHttpClientResponse].handler({x: Buffer => handler.handle(x)})
    this
  }
```

Maybe null application to handler methods could. be forwarded directly to the  java.api without wrapping.

Nulls are not idiomatic in scala but I think this is fine in this case (there are no way to get back the reference so throwing NPE)

**Comment by codepitbull** [comment]
Ah, good catch!
I will take care of this.

**Comment by codepitbull** [comment]
I have just merged a fix for this.
Will be part of 3.8.
