### ISSUE TITLE
Support for scala 2.13

### ISSUE THREAD

**Issue by miteshaghera** [vert-x3/vertx-lang-scala#83]
https://github.com/scala/scala/releases/tag/v2.13.0

**Comment by miteshaghera** [comment]
I had done some initial work [here](https://github.com/miteshaghera/vertx-lang-scala/tree/scala_2.13). If anyone can take a loot at this.

Still build is failing because one [test](https://github.com/miteshaghera/vertx-lang-scala/blob/fe5e141a1ebbcabef5a6509c3979409ae9a3ea26/vertx-lang-scala/src/test/scala/io/vertx/lang/scala/tck/CollectionTCKTest.scala#L122) is not being passed.

**Comment by codepitbull** [comment]
Hey, so I played around with it tonight and got it working:
https://github.com/vert-x3/vertx-lang-scala/tree/3.8_2.13

I am currently discussing with the other maintainers how we are going to ship it since we will have to support/release two version from now on: 2.12 and 2.13.

If you are interested in work on vertx-lang-scala 4 then you can check here:
https://github.com/vert-x3/vertx-lang-scala/tree/4.0

**Comment by miteshaghera** [comment]
Thanks @codepitbull, I'll take a look at vert-lang-scala 4.

**Comment by leosilvadev** [comment]
@codepitbull I am a bit lost on the roadmap for scala support, are there changes going on for vert.x 4? How can I keep up to date with it? Is help needed?

**Comment by codepitbull** [comment]
@leosilvadev I wrote a blog post on this a while ago:
https://vertx.io/blog/eclipse-vert-x-for-scala-next-steps/

The current master already has the new implementation of vertx-lang-scala so you can try iot out right now (input would be very welcome).

We are currently in the final stages, preparing for Vert.x 4.

The documentation is building but I am waiting until the modules are all fixed so I can do a new round of builds.

The new version should bbe part of the first release candidate of vert.x 4.

**Comment by codepitbull** [comment]
And on a side note: Thanks to @aesteve we are also woring on Scala 3 (Dotty) support.
I am not yet sure when and how this will be available but it will be based on the current implementation.

**Comment by leosilvadev** [comment]
Hello guys, sorry to ping here again, I just wonder if there is any update about the topic since Vert.x 4 was released
Is there any help needed?

**Comment by aesteve** [comment]
I tried to give it a look this week-end but faced codegen issues, I don't know how to tackle these unfortunately :(

**Comment by leosilvadev** [comment]
@aesteve do you have it on some specific branch I could take a look too?

**Comment by aesteve** [comment]
No I just forked this repo, switched to the 4.0 branch, and tried to update poms to use 4.0.0.
(unfortunately I gave up and did not push my experiments)
I made some tiny adjustments to codegen (which are discussed on Vert.x discord, channel `vertx-scala-lang`) but codegen crashed at build time and I'm stuck here.

**Comment by demming** [comment]
Hi, any updates on this issue? Really looking forward to Scala 3 bindings with Vert.x 4. What's the sentiment right now and going forward? Any efforts being made to tackle it? Would gladly try to help if I knew where to start.

**Comment by oliver-brm** [comment]
We're supporting Scala 3 and Vert.x 4 in the meantime. I'll close this issue. Thanks for the work you put in, folks.
