### ISSUE TITLE
sbt - Support for including resources to use CommandFactory

### ISSUE THREAD

**Issue by swetharamaiah** [vert-x3/vertx-lang-scala#85]
When trying to run a vertx app as a fat jar using `java -jar vertx-app.jar` command, following error occurs:
```
$ java -jar vertx-server.jar 
The command 'run' is not a valid command.
See 'java -jar vertx-server.jar --help'
```
Based on the comments in https://groups.google.com/forum/#!topic/vertx/CMgv1gSpa1s, it appears that we need to add a transformer to include resources like the `CommmandFactory` and `VerticleFactory` using **maven shade plugin** which appears to be missing when using `sbt`.

**Comment by codepitbull** [comment]
I will take care of it.

**Comment by codepitbull** [comment]
I just tested using the g8-project I created.
Please use the following to create a project:
`sbt new vert-x3/vertx-scala.g8`

Afterwards run `sbt assembly` in the newly created project.

You will then have `target/scala-2.12/<projectname>assembly-0.1.0-SNAPSHOT.jar` which works perfectly fine when executed using `javae -jar`
