### ISSUE TITLE
Lack of `Reactive PostgreSQL client`

### ISSUE THREAD

**Issue by UkonnRa** [vert-x3/vertx-lang-scala#88]
Is [Reactive PostgreSQL client](https://vertx.io/docs/vertx-pg-client/java/) not usable is vertx-scala?

**Comment by codepitbull** [comment]
It will be soon.
This slipped through the cracks while implementing the new stuff.
I will add this after vertx-scala is up to date with the current changes to vertx.

**Comment by codepitbull** [comment]
It's now in :) (together with several other ones I missed)
https://github.com/vert-x3/vertx-lang-scala/commit /fcbb9a4f9c902a0b8d20bacce5fb8a566a08b125#diff-18acc0ee1bb1cc1a9f96c9aa9d3cf6a9
