### ISSUE TITLE
Cannot send event bus message between 2 verticles

### ISSUE THREAD

**Issue by cinterloper** [vert-x3/vertx-lang-scala#94]
### Version

version: 3.9.1

### Context

I created a project that spawns 2 verticles, an eventbus producer and an eventbus consumer

A reproducer can be found here: https://github.com/cinterloper/vertx_scala_eb_repro
if you run this with sbt fgRun , it will produce console logs that indicate messages are being sent, but no messages indicating they are being received

**Comment by codepitbull** [comment]
Hey, I just got asround to take a look:

Please use the following, more scalaish-way of registering the handler.
```
vertx.eventBus().consumer(CHANNEL, (ev: Message[AnyVal]) => println(s"got ${ev}"))
```

I tested it with your project and that does the trick :)

**Comment by tsegismont** [comment]
Thanks Jochen.

There is also this question on the forum
https://groups.google.com/g/vertx/c/4m5FpoRDyLQ/m/gvWfJ6ncDQAJ

Would you mind taking a look?
